"""initial

Revision ID: 2cccc14b8452
Revises: 
Create Date: 2026-10-01 20:23:23.797991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2cccc14b8452'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competences',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domaine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapitre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intitule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('niveau_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulte', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seuil_maitrise', sa.JSON(), nullable=True),
    sa.Column('erreurs_types', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eleves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudonyme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_creation', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleves_pseudonyme'), 'eleves', ['pseudonyme'], unique=True)
    op.create_table('blocs_protocole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('notion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('dates', sa.JSON(), nullable=True),
    sa.Column('mesures', sa.JSON(), nullable=True),
    sa.Column('fidelite', sa.JSON(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocs_protocole_eleve_id'), 'blocs_protocole', ['eleve_id'], unique=False)
    op.create_table('etat_competence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nb_reussites', sa.Integer(), nullable=False),
    sa.Column('nb_tentatives', sa.Integer(), nullable=False),
    sa.Column('derniere_date', sa.Date(), nullable=True),
    sa.Column('date_acquisition', sa.Date(), nullable=True),
    sa.Column('date_consolidation', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competences.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etat_competence_eleve_id'), 'etat_competence', ['eleve_id'], unique=False)
    op.create_table('gabarits_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('competence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulte', sa.Integer(), nullable=False),
    sa.Column('format_reponse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('reponse', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('methode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('derives', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('contact_famille', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consentement', sa.Boolean(), nullable=False),
    sa.Column('date_consentement', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eleve_id')
    )
    op.create_table('indicateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valeur', sa.JSON(), nullable=True),
    sa.Column('periode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_calcul', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicateurs_eleve_id'), 'indicateurs', ['eleve_id'], unique=False)
    op.create_table('journal_profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('champ', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ancienne_valeur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nouvelle_valeur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raison', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_profil_eleve_id'), 'journal_profil', ['eleve_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('date_creation', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('cible_noeuds', sa.JSON(), nullable=True),
    sa.Column('noeuds_ordonnes', sa.JSON(), nullable=True),
    sa.Column('echeances', sa.JSON(), nullable=True),
    sa.Column('statut', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_eleve_id'), 'plan', ['eleve_id'], unique=False)
    op.create_table('prerequis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cible_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_arete', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cible_id'], ['competences.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['competences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prerequis_cible_id'), 'prerequis', ['cible_id'], unique=False)
    op.create_table('profils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('date_version', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('raison', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('champs', sa.JSON(), nullable=True),
    sa.Column('statuts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profils_eleve_id'), 'profils', ['eleve_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('date_fin', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_eleve_id'), 'sessions', ['eleve_id'], unique=False)
    op.create_table('items_generes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gabarit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('enonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reponse_attendue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_generation', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['gabarit_id'], ['gabarits_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valeur', sa.JSON(), nullable=True),
    sa.Column('date', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_eleve_id'), 'observations', ['eleve_id'], unique=False)
    op.create_table('reponses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('competence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reponse_eleve', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('est_correct', sa.Boolean(), nullable=True),
    sa.Column('temps_reponse_ms', sa.Integer(), nullable=True),
    sa.Column('confiance_annoncee', sa.Integer(), nullable=True),
    sa.Column('type_erreur', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('methode_observee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('est_controle', sa.Boolean(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competences.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items_generes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reponses_eleve_id'), 'reponses', ['eleve_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reponses_eleve_id'), table_name='reponses')
    op.drop_table('reponses')
    op.drop_index(op.f('ix_observations_eleve_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('items_generes')
    op.drop_index(op.f('ix_sessions_eleve_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_profils_eleve_id'), table_name='profils')
    op.drop_table('profils')
    op.drop_index(op.f('ix_prerequis_cible_id'), table_name='prerequis')
    op.drop_table('prerequis')
    op.drop_index(op.f('ix_plan_eleve_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_journal_profil_eleve_id'), table_name='journal_profil')
    op.drop_table('journal_profil')
    op.drop_index(op.f('ix_indicateurs_eleve_id'), table_name='indicateurs')
    op.drop_table('indicateurs')
    op.drop_table('identites')
    op.drop_table('gabarits_items')
    op.drop_index(op.f('ix_etat_competence_eleve_id'), table_name='etat_competence')
    op.drop_table('etat_competence')
    op.drop_index(op.f('ix_blocs_protocole_eleve_id'), table_name='blocs_protocole')
    op.drop_table('blocs_protocole')
    op.drop_index(op.f('ix_eleves_pseudonyme'), table_name='eleves')
    op.drop_table('eleves')
    op.drop_table('competences')
    # ### end Alembic commands ###
